# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-06 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170519_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('docfile', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
    ]
