# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-07 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20170906_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
